#############################################################################
# Makefile for building: 595-mosquito.app/Contents/MacOS/595-mosquito
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  595-mosquito.pro
# Template: app
# Command: /Users/chris/Documents/cit595/Qt/5.5/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile 595-mosquito.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I../../../Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers -I../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.5/clang_64/mkspecs/macx-clang -F/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib
QMAKE         = /Users/chris/Documents/cit595/Qt/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = 595-mosquito1.0.0
DISTDIR = /Users/chris/Documents/cit595/homework/homework6/595-mosquito/.tmp/595-mosquito1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		glwidget.cpp \
		window.cpp \
		mosquito.cpp \
		helper.cpp \
		light.cpp \
		board.cpp \
		wall.cpp \
		frog.cpp \
		player.cpp \
		myplayer.cpp moc_glwidget.cpp \
		moc_window.cpp
OBJECTS       = main.o \
		glwidget.o \
		window.o \
		mosquito.o \
		helper.o \
		light.o \
		board.o \
		wall.o \
		frog.o \
		player.o \
		myplayer.o \
		moc_glwidget.o \
		moc_window.o
DIST          = wall_setup.txt \
		../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		595-mosquito.pro glwidget.h \
		window.h \
		mosquito.h \
		helper.h \
		light.h \
		board.h \
		wall.h \
		frog.h \
		player.h \
		myplayer.h main.cpp \
		glwidget.cpp \
		window.cpp \
		mosquito.cpp \
		helper.cpp \
		light.cpp \
		board.cpp \
		wall.cpp \
		frog.cpp \
		player.cpp \
		myplayer.cpp
QMAKE_TARGET  = 595-mosquito
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = 595-mosquito.app/Contents/MacOS/595-mosquito

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d 595-mosquito.app/Contents/MacOS/ || mkdir -p 595-mosquito.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 595-mosquito.pro ../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		595-mosquito.pro \
		/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile 595-mosquito.pro
../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.5/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.5/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.5/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.5/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.5/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.5/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf:
../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.5/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.5/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.5/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.5/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.5/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.5/clang_64/mkspecs/features/lex.prf:
595-mosquito.pro:
/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile 595-mosquito.pro

qmake_all: FORCE

595-mosquito.app/Contents/PkgInfo: 
	@test -d 595-mosquito.app/Contents || mkdir -p 595-mosquito.app/Contents
	@$(DEL_FILE) 595-mosquito.app/Contents/PkgInfo
	@echo "APPL????" > 595-mosquito.app/Contents/PkgInfo
595-mosquito.app/Contents/Resources/empty.lproj: 
	@test -d 595-mosquito.app/Contents/Resources || mkdir -p 595-mosquito.app/Contents/Resources
	@touch 595-mosquito.app/Contents/Resources/empty.lproj
	
595-mosquito.app/Contents/Info.plist: 
	@test -d 595-mosquito.app/Contents || mkdir -p 595-mosquito.app/Contents
	@$(DEL_FILE) 595-mosquito.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.595-mosquito,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,595-mosquito,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >595-mosquito.app/Contents/Info.plist

all: Makefile \
		595-mosquito.app/Contents/PkgInfo \
		595-mosquito.app/Contents/Resources/empty.lproj \
		595-mosquito.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents glwidget.h window.h mosquito.h helper.h light.h board.h wall.h frog.h player.h myplayer.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp glwidget.cpp window.cpp mosquito.cpp helper.cpp light.cpp board.cpp wall.cpp frog.cpp player.cpp myplayer.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r 595-mosquito.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_glwidget.cpp moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_glwidget.cpp moc_window.cpp
moc_glwidget.cpp: ../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		glwidget.h
	/Users/chris/Documents/cit595/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chris/Documents/cit595/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/chris/Documents/cit595/homework/homework6/595-mosquito -I/Users/chris/Documents/cit595/homework/homework6/595-mosquito/include -I/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers -I/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib glwidget.h -o moc_glwidget.cpp

moc_window.cpp: helper.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QPen \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		board.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvector.h \
		mosquito.h \
		include/glm/glm.hpp \
		include/glm/detail/_fixes.hpp \
		include/glm/fwd.hpp \
		include/glm/detail/type_int.hpp \
		include/glm/detail/setup.hpp \
		include/glm/detail/type_float.hpp \
		include/glm/detail/type_vec.hpp \
		include/glm/detail/precision.hpp \
		include/glm/detail/type_mat.hpp \
		include/glm/vec2.hpp \
		include/glm/detail/type_vec2.hpp \
		include/glm/detail/_swizzle.hpp \
		include/glm/detail/_swizzle_func.hpp \
		include/glm/detail/type_vec2.inl \
		include/glm/vec3.hpp \
		include/glm/detail/type_vec3.hpp \
		include/glm/detail/type_vec3.inl \
		include/glm/vec4.hpp \
		include/glm/detail/type_vec4.hpp \
		include/glm/detail/type_vec4.inl \
		include/glm/mat2x2.hpp \
		include/glm/detail/type_mat2x2.hpp \
		include/glm/detail/type_mat2x2.inl \
		include/glm/mat2x3.hpp \
		include/glm/detail/type_mat2x3.hpp \
		include/glm/detail/type_mat2x3.inl \
		include/glm/mat2x4.hpp \
		include/glm/detail/type_mat2x4.hpp \
		include/glm/detail/type_mat2x4.inl \
		include/glm/mat3x2.hpp \
		include/glm/detail/type_mat3x2.hpp \
		include/glm/detail/type_mat3x2.inl \
		include/glm/mat3x3.hpp \
		include/glm/detail/type_mat3x3.hpp \
		include/glm/detail/type_mat3x3.inl \
		include/glm/mat3x4.hpp \
		include/glm/detail/type_mat3x4.hpp \
		include/glm/detail/type_mat3x4.inl \
		include/glm/mat4x2.hpp \
		include/glm/detail/type_mat4x2.hpp \
		include/glm/detail/type_mat4x2.inl \
		include/glm/mat4x3.hpp \
		include/glm/detail/type_mat4x3.hpp \
		include/glm/detail/type_mat4x3.inl \
		include/glm/mat4x4.hpp \
		include/glm/detail/type_mat4x4.hpp \
		include/glm/detail/type_mat4x4.inl \
		include/glm/trigonometric.hpp \
		include/glm/detail/func_trigonometric.hpp \
		include/glm/detail/func_trigonometric.inl \
		include/glm/detail/_vectorize.hpp \
		include/glm/detail/type_vec1.hpp \
		include/glm/detail/type_vec1.inl \
		include/glm/exponential.hpp \
		include/glm/detail/func_exponential.hpp \
		include/glm/detail/func_exponential.inl \
		include/glm/detail/func_vector_relational.hpp \
		include/glm/detail/func_vector_relational.inl \
		include/glm/common.hpp \
		include/glm/detail/func_common.hpp \
		include/glm/detail/func_common.inl \
		include/glm/packing.hpp \
		include/glm/detail/func_packing.hpp \
		include/glm/detail/func_packing.inl \
		include/glm/detail/type_half.hpp \
		include/glm/detail/type_half.inl \
		include/glm/geometric.hpp \
		include/glm/detail/func_geometric.hpp \
		include/glm/detail/func_geometric.inl \
		include/glm/matrix.hpp \
		include/glm/detail/func_matrix.hpp \
		include/glm/detail/func_matrix.inl \
		include/glm/vector_relational.hpp \
		include/glm/integer.hpp \
		include/glm/detail/func_integer.hpp \
		include/glm/detail/func_integer.inl \
		light.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		wall.h \
		frog.h \
		player.h \
		myplayer.h \
		glwidget.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		window.h
	/Users/chris/Documents/cit595/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/chris/Documents/cit595/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/chris/Documents/cit595/homework/homework6/595-mosquito -I/Users/chris/Documents/cit595/homework/homework6/595-mosquito/include -I/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtOpenGL.framework/Headers -I/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/chris/Documents/cit595/Qt/5.5/clang_64/lib window.h -o moc_window.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		glwidget.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h
	/Users/chris/Documents/cit595/Qt/5.5/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp window.h \
		helper.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QPen \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		board.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvector.h \
		mosquito.h \
		include/glm/glm.hpp \
		include/glm/detail/_fixes.hpp \
		include/glm/fwd.hpp \
		include/glm/detail/type_int.hpp \
		include/glm/detail/setup.hpp \
		include/glm/detail/type_float.hpp \
		include/glm/detail/type_vec.hpp \
		include/glm/detail/precision.hpp \
		include/glm/detail/type_mat.hpp \
		include/glm/vec2.hpp \
		include/glm/detail/type_vec2.hpp \
		include/glm/detail/_swizzle.hpp \
		include/glm/detail/_swizzle_func.hpp \
		include/glm/detail/type_vec2.inl \
		include/glm/vec3.hpp \
		include/glm/detail/type_vec3.hpp \
		include/glm/detail/type_vec3.inl \
		include/glm/vec4.hpp \
		include/glm/detail/type_vec4.hpp \
		include/glm/detail/type_vec4.inl \
		include/glm/mat2x2.hpp \
		include/glm/detail/type_mat2x2.hpp \
		include/glm/detail/type_mat2x2.inl \
		include/glm/mat2x3.hpp \
		include/glm/detail/type_mat2x3.hpp \
		include/glm/detail/type_mat2x3.inl \
		include/glm/mat2x4.hpp \
		include/glm/detail/type_mat2x4.hpp \
		include/glm/detail/type_mat2x4.inl \
		include/glm/mat3x2.hpp \
		include/glm/detail/type_mat3x2.hpp \
		include/glm/detail/type_mat3x2.inl \
		include/glm/mat3x3.hpp \
		include/glm/detail/type_mat3x3.hpp \
		include/glm/detail/type_mat3x3.inl \
		include/glm/mat3x4.hpp \
		include/glm/detail/type_mat3x4.hpp \
		include/glm/detail/type_mat3x4.inl \
		include/glm/mat4x2.hpp \
		include/glm/detail/type_mat4x2.hpp \
		include/glm/detail/type_mat4x2.inl \
		include/glm/mat4x3.hpp \
		include/glm/detail/type_mat4x3.hpp \
		include/glm/detail/type_mat4x3.inl \
		include/glm/mat4x4.hpp \
		include/glm/detail/type_mat4x4.hpp \
		include/glm/detail/type_mat4x4.inl \
		include/glm/trigonometric.hpp \
		include/glm/detail/func_trigonometric.hpp \
		include/glm/detail/func_trigonometric.inl \
		include/glm/detail/_vectorize.hpp \
		include/glm/detail/type_vec1.hpp \
		include/glm/detail/type_vec1.inl \
		include/glm/exponential.hpp \
		include/glm/detail/func_exponential.hpp \
		include/glm/detail/func_exponential.inl \
		include/glm/detail/func_vector_relational.hpp \
		include/glm/detail/func_vector_relational.inl \
		include/glm/common.hpp \
		include/glm/detail/func_common.hpp \
		include/glm/detail/func_common.inl \
		include/glm/packing.hpp \
		include/glm/detail/func_packing.hpp \
		include/glm/detail/func_packing.inl \
		include/glm/detail/type_half.hpp \
		include/glm/detail/type_half.inl \
		include/glm/geometric.hpp \
		include/glm/detail/func_geometric.hpp \
		include/glm/detail/func_geometric.inl \
		include/glm/matrix.hpp \
		include/glm/detail/func_matrix.hpp \
		include/glm/detail/func_matrix.inl \
		include/glm/vector_relational.hpp \
		include/glm/integer.hpp \
		include/glm/detail/func_integer.hpp \
		include/glm/detail/func_integer.inl \
		light.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		wall.h \
		frog.h \
		player.h \
		myplayer.h \
		glwidget.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QSurfaceFormat \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

glwidget.o: glwidget.cpp glwidget.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		helper.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QPen \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		board.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvector.h \
		mosquito.h \
		include/glm/glm.hpp \
		include/glm/detail/_fixes.hpp \
		include/glm/fwd.hpp \
		include/glm/detail/type_int.hpp \
		include/glm/detail/setup.hpp \
		include/glm/detail/type_float.hpp \
		include/glm/detail/type_vec.hpp \
		include/glm/detail/precision.hpp \
		include/glm/detail/type_mat.hpp \
		include/glm/vec2.hpp \
		include/glm/detail/type_vec2.hpp \
		include/glm/detail/_swizzle.hpp \
		include/glm/detail/_swizzle_func.hpp \
		include/glm/detail/type_vec2.inl \
		include/glm/vec3.hpp \
		include/glm/detail/type_vec3.hpp \
		include/glm/detail/type_vec3.inl \
		include/glm/vec4.hpp \
		include/glm/detail/type_vec4.hpp \
		include/glm/detail/type_vec4.inl \
		include/glm/mat2x2.hpp \
		include/glm/detail/type_mat2x2.hpp \
		include/glm/detail/type_mat2x2.inl \
		include/glm/mat2x3.hpp \
		include/glm/detail/type_mat2x3.hpp \
		include/glm/detail/type_mat2x3.inl \
		include/glm/mat2x4.hpp \
		include/glm/detail/type_mat2x4.hpp \
		include/glm/detail/type_mat2x4.inl \
		include/glm/mat3x2.hpp \
		include/glm/detail/type_mat3x2.hpp \
		include/glm/detail/type_mat3x2.inl \
		include/glm/mat3x3.hpp \
		include/glm/detail/type_mat3x3.hpp \
		include/glm/detail/type_mat3x3.inl \
		include/glm/mat3x4.hpp \
		include/glm/detail/type_mat3x4.hpp \
		include/glm/detail/type_mat3x4.inl \
		include/glm/mat4x2.hpp \
		include/glm/detail/type_mat4x2.hpp \
		include/glm/detail/type_mat4x2.inl \
		include/glm/mat4x3.hpp \
		include/glm/detail/type_mat4x3.hpp \
		include/glm/detail/type_mat4x3.inl \
		include/glm/mat4x4.hpp \
		include/glm/detail/type_mat4x4.hpp \
		include/glm/detail/type_mat4x4.inl \
		include/glm/trigonometric.hpp \
		include/glm/detail/func_trigonometric.hpp \
		include/glm/detail/func_trigonometric.inl \
		include/glm/detail/_vectorize.hpp \
		include/glm/detail/type_vec1.hpp \
		include/glm/detail/type_vec1.inl \
		include/glm/exponential.hpp \
		include/glm/detail/func_exponential.hpp \
		include/glm/detail/func_exponential.inl \
		include/glm/detail/func_vector_relational.hpp \
		include/glm/detail/func_vector_relational.inl \
		include/glm/common.hpp \
		include/glm/detail/func_common.hpp \
		include/glm/detail/func_common.inl \
		include/glm/packing.hpp \
		include/glm/detail/func_packing.hpp \
		include/glm/detail/func_packing.inl \
		include/glm/detail/type_half.hpp \
		include/glm/detail/type_half.inl \
		include/glm/geometric.hpp \
		include/glm/detail/func_geometric.hpp \
		include/glm/detail/func_geometric.inl \
		include/glm/matrix.hpp \
		include/glm/detail/func_matrix.hpp \
		include/glm/detail/func_matrix.inl \
		include/glm/vector_relational.hpp \
		include/glm/integer.hpp \
		include/glm/detail/func_integer.hpp \
		include/glm/detail/func_integer.inl \
		light.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		wall.h \
		frog.h \
		player.h \
		myplayer.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

window.o: window.cpp glwidget.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		window.h \
		helper.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QPen \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		board.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvector.h \
		mosquito.h \
		include/glm/glm.hpp \
		include/glm/detail/_fixes.hpp \
		include/glm/fwd.hpp \
		include/glm/detail/type_int.hpp \
		include/glm/detail/setup.hpp \
		include/glm/detail/type_float.hpp \
		include/glm/detail/type_vec.hpp \
		include/glm/detail/precision.hpp \
		include/glm/detail/type_mat.hpp \
		include/glm/vec2.hpp \
		include/glm/detail/type_vec2.hpp \
		include/glm/detail/_swizzle.hpp \
		include/glm/detail/_swizzle_func.hpp \
		include/glm/detail/type_vec2.inl \
		include/glm/vec3.hpp \
		include/glm/detail/type_vec3.hpp \
		include/glm/detail/type_vec3.inl \
		include/glm/vec4.hpp \
		include/glm/detail/type_vec4.hpp \
		include/glm/detail/type_vec4.inl \
		include/glm/mat2x2.hpp \
		include/glm/detail/type_mat2x2.hpp \
		include/glm/detail/type_mat2x2.inl \
		include/glm/mat2x3.hpp \
		include/glm/detail/type_mat2x3.hpp \
		include/glm/detail/type_mat2x3.inl \
		include/glm/mat2x4.hpp \
		include/glm/detail/type_mat2x4.hpp \
		include/glm/detail/type_mat2x4.inl \
		include/glm/mat3x2.hpp \
		include/glm/detail/type_mat3x2.hpp \
		include/glm/detail/type_mat3x2.inl \
		include/glm/mat3x3.hpp \
		include/glm/detail/type_mat3x3.hpp \
		include/glm/detail/type_mat3x3.inl \
		include/glm/mat3x4.hpp \
		include/glm/detail/type_mat3x4.hpp \
		include/glm/detail/type_mat3x4.inl \
		include/glm/mat4x2.hpp \
		include/glm/detail/type_mat4x2.hpp \
		include/glm/detail/type_mat4x2.inl \
		include/glm/mat4x3.hpp \
		include/glm/detail/type_mat4x3.hpp \
		include/glm/detail/type_mat4x3.inl \
		include/glm/mat4x4.hpp \
		include/glm/detail/type_mat4x4.hpp \
		include/glm/detail/type_mat4x4.inl \
		include/glm/trigonometric.hpp \
		include/glm/detail/func_trigonometric.hpp \
		include/glm/detail/func_trigonometric.inl \
		include/glm/detail/_vectorize.hpp \
		include/glm/detail/type_vec1.hpp \
		include/glm/detail/type_vec1.inl \
		include/glm/exponential.hpp \
		include/glm/detail/func_exponential.hpp \
		include/glm/detail/func_exponential.inl \
		include/glm/detail/func_vector_relational.hpp \
		include/glm/detail/func_vector_relational.inl \
		include/glm/common.hpp \
		include/glm/detail/func_common.hpp \
		include/glm/detail/func_common.inl \
		include/glm/packing.hpp \
		include/glm/detail/func_packing.hpp \
		include/glm/detail/func_packing.inl \
		include/glm/detail/type_half.hpp \
		include/glm/detail/type_half.inl \
		include/glm/geometric.hpp \
		include/glm/detail/func_geometric.hpp \
		include/glm/detail/func_geometric.inl \
		include/glm/matrix.hpp \
		include/glm/detail/func_matrix.hpp \
		include/glm/detail/func_matrix.inl \
		include/glm/vector_relational.hpp \
		include/glm/integer.hpp \
		include/glm/detail/func_integer.hpp \
		include/glm/detail/func_integer.inl \
		light.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		wall.h \
		frog.h \
		player.h \
		myplayer.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

mosquito.o: mosquito.cpp mosquito.h \
		include/glm/glm.hpp \
		include/glm/detail/_fixes.hpp \
		include/glm/fwd.hpp \
		include/glm/detail/type_int.hpp \
		include/glm/detail/setup.hpp \
		include/glm/detail/type_float.hpp \
		include/glm/detail/type_vec.hpp \
		include/glm/detail/precision.hpp \
		include/glm/detail/type_mat.hpp \
		include/glm/vec2.hpp \
		include/glm/detail/type_vec2.hpp \
		include/glm/detail/_swizzle.hpp \
		include/glm/detail/_swizzle_func.hpp \
		include/glm/detail/type_vec2.inl \
		include/glm/vec3.hpp \
		include/glm/detail/type_vec3.hpp \
		include/glm/detail/type_vec3.inl \
		include/glm/vec4.hpp \
		include/glm/detail/type_vec4.hpp \
		include/glm/detail/type_vec4.inl \
		include/glm/mat2x2.hpp \
		include/glm/detail/type_mat2x2.hpp \
		include/glm/detail/type_mat2x2.inl \
		include/glm/mat2x3.hpp \
		include/glm/detail/type_mat2x3.hpp \
		include/glm/detail/type_mat2x3.inl \
		include/glm/mat2x4.hpp \
		include/glm/detail/type_mat2x4.hpp \
		include/glm/detail/type_mat2x4.inl \
		include/glm/mat3x2.hpp \
		include/glm/detail/type_mat3x2.hpp \
		include/glm/detail/type_mat3x2.inl \
		include/glm/mat3x3.hpp \
		include/glm/detail/type_mat3x3.hpp \
		include/glm/detail/type_mat3x3.inl \
		include/glm/mat3x4.hpp \
		include/glm/detail/type_mat3x4.hpp \
		include/glm/detail/type_mat3x4.inl \
		include/glm/mat4x2.hpp \
		include/glm/detail/type_mat4x2.hpp \
		include/glm/detail/type_mat4x2.inl \
		include/glm/mat4x3.hpp \
		include/glm/detail/type_mat4x3.hpp \
		include/glm/detail/type_mat4x3.inl \
		include/glm/mat4x4.hpp \
		include/glm/detail/type_mat4x4.hpp \
		include/glm/detail/type_mat4x4.inl \
		include/glm/trigonometric.hpp \
		include/glm/detail/func_trigonometric.hpp \
		include/glm/detail/func_trigonometric.inl \
		include/glm/detail/_vectorize.hpp \
		include/glm/detail/type_vec1.hpp \
		include/glm/detail/type_vec1.inl \
		include/glm/exponential.hpp \
		include/glm/detail/func_exponential.hpp \
		include/glm/detail/func_exponential.inl \
		include/glm/detail/func_vector_relational.hpp \
		include/glm/detail/func_vector_relational.inl \
		include/glm/common.hpp \
		include/glm/detail/func_common.hpp \
		include/glm/detail/func_common.inl \
		include/glm/packing.hpp \
		include/glm/detail/func_packing.hpp \
		include/glm/detail/func_packing.inl \
		include/glm/detail/type_half.hpp \
		include/glm/detail/type_half.inl \
		include/glm/geometric.hpp \
		include/glm/detail/func_geometric.hpp \
		include/glm/detail/func_geometric.inl \
		include/glm/matrix.hpp \
		include/glm/detail/func_matrix.hpp \
		include/glm/detail/func_matrix.inl \
		include/glm/vector_relational.hpp \
		include/glm/integer.hpp \
		include/glm/detail/func_integer.hpp \
		include/glm/detail/func_integer.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mosquito.o mosquito.cpp

helper.o: helper.cpp helper.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QPen \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		board.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvector.h \
		mosquito.h \
		include/glm/glm.hpp \
		include/glm/detail/_fixes.hpp \
		include/glm/fwd.hpp \
		include/glm/detail/type_int.hpp \
		include/glm/detail/setup.hpp \
		include/glm/detail/type_float.hpp \
		include/glm/detail/type_vec.hpp \
		include/glm/detail/precision.hpp \
		include/glm/detail/type_mat.hpp \
		include/glm/vec2.hpp \
		include/glm/detail/type_vec2.hpp \
		include/glm/detail/_swizzle.hpp \
		include/glm/detail/_swizzle_func.hpp \
		include/glm/detail/type_vec2.inl \
		include/glm/vec3.hpp \
		include/glm/detail/type_vec3.hpp \
		include/glm/detail/type_vec3.inl \
		include/glm/vec4.hpp \
		include/glm/detail/type_vec4.hpp \
		include/glm/detail/type_vec4.inl \
		include/glm/mat2x2.hpp \
		include/glm/detail/type_mat2x2.hpp \
		include/glm/detail/type_mat2x2.inl \
		include/glm/mat2x3.hpp \
		include/glm/detail/type_mat2x3.hpp \
		include/glm/detail/type_mat2x3.inl \
		include/glm/mat2x4.hpp \
		include/glm/detail/type_mat2x4.hpp \
		include/glm/detail/type_mat2x4.inl \
		include/glm/mat3x2.hpp \
		include/glm/detail/type_mat3x2.hpp \
		include/glm/detail/type_mat3x2.inl \
		include/glm/mat3x3.hpp \
		include/glm/detail/type_mat3x3.hpp \
		include/glm/detail/type_mat3x3.inl \
		include/glm/mat3x4.hpp \
		include/glm/detail/type_mat3x4.hpp \
		include/glm/detail/type_mat3x4.inl \
		include/glm/mat4x2.hpp \
		include/glm/detail/type_mat4x2.hpp \
		include/glm/detail/type_mat4x2.inl \
		include/glm/mat4x3.hpp \
		include/glm/detail/type_mat4x3.hpp \
		include/glm/detail/type_mat4x3.inl \
		include/glm/mat4x4.hpp \
		include/glm/detail/type_mat4x4.hpp \
		include/glm/detail/type_mat4x4.inl \
		include/glm/trigonometric.hpp \
		include/glm/detail/func_trigonometric.hpp \
		include/glm/detail/func_trigonometric.inl \
		include/glm/detail/_vectorize.hpp \
		include/glm/detail/type_vec1.hpp \
		include/glm/detail/type_vec1.inl \
		include/glm/exponential.hpp \
		include/glm/detail/func_exponential.hpp \
		include/glm/detail/func_exponential.inl \
		include/glm/detail/func_vector_relational.hpp \
		include/glm/detail/func_vector_relational.inl \
		include/glm/common.hpp \
		include/glm/detail/func_common.hpp \
		include/glm/detail/func_common.inl \
		include/glm/packing.hpp \
		include/glm/detail/func_packing.hpp \
		include/glm/detail/func_packing.inl \
		include/glm/detail/type_half.hpp \
		include/glm/detail/type_half.inl \
		include/glm/geometric.hpp \
		include/glm/detail/func_geometric.hpp \
		include/glm/detail/func_geometric.inl \
		include/glm/matrix.hpp \
		include/glm/detail/func_matrix.hpp \
		include/glm/detail/func_matrix.inl \
		include/glm/vector_relational.hpp \
		include/glm/integer.hpp \
		include/glm/detail/func_integer.hpp \
		include/glm/detail/func_integer.inl \
		light.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		wall.h \
		frog.h \
		player.h \
		myplayer.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helper.o helper.cpp

light.o: light.cpp light.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		include/glm/glm.hpp \
		include/glm/detail/_fixes.hpp \
		include/glm/fwd.hpp \
		include/glm/detail/type_int.hpp \
		include/glm/detail/setup.hpp \
		include/glm/detail/type_float.hpp \
		include/glm/detail/type_vec.hpp \
		include/glm/detail/precision.hpp \
		include/glm/detail/type_mat.hpp \
		include/glm/vec2.hpp \
		include/glm/detail/type_vec2.hpp \
		include/glm/detail/_swizzle.hpp \
		include/glm/detail/_swizzle_func.hpp \
		include/glm/detail/type_vec2.inl \
		include/glm/vec3.hpp \
		include/glm/detail/type_vec3.hpp \
		include/glm/detail/type_vec3.inl \
		include/glm/vec4.hpp \
		include/glm/detail/type_vec4.hpp \
		include/glm/detail/type_vec4.inl \
		include/glm/mat2x2.hpp \
		include/glm/detail/type_mat2x2.hpp \
		include/glm/detail/type_mat2x2.inl \
		include/glm/mat2x3.hpp \
		include/glm/detail/type_mat2x3.hpp \
		include/glm/detail/type_mat2x3.inl \
		include/glm/mat2x4.hpp \
		include/glm/detail/type_mat2x4.hpp \
		include/glm/detail/type_mat2x4.inl \
		include/glm/mat3x2.hpp \
		include/glm/detail/type_mat3x2.hpp \
		include/glm/detail/type_mat3x2.inl \
		include/glm/mat3x3.hpp \
		include/glm/detail/type_mat3x3.hpp \
		include/glm/detail/type_mat3x3.inl \
		include/glm/mat3x4.hpp \
		include/glm/detail/type_mat3x4.hpp \
		include/glm/detail/type_mat3x4.inl \
		include/glm/mat4x2.hpp \
		include/glm/detail/type_mat4x2.hpp \
		include/glm/detail/type_mat4x2.inl \
		include/glm/mat4x3.hpp \
		include/glm/detail/type_mat4x3.hpp \
		include/glm/detail/type_mat4x3.inl \
		include/glm/mat4x4.hpp \
		include/glm/detail/type_mat4x4.hpp \
		include/glm/detail/type_mat4x4.inl \
		include/glm/trigonometric.hpp \
		include/glm/detail/func_trigonometric.hpp \
		include/glm/detail/func_trigonometric.inl \
		include/glm/detail/_vectorize.hpp \
		include/glm/detail/type_vec1.hpp \
		include/glm/detail/type_vec1.inl \
		include/glm/exponential.hpp \
		include/glm/detail/func_exponential.hpp \
		include/glm/detail/func_exponential.inl \
		include/glm/detail/func_vector_relational.hpp \
		include/glm/detail/func_vector_relational.inl \
		include/glm/common.hpp \
		include/glm/detail/func_common.hpp \
		include/glm/detail/func_common.inl \
		include/glm/packing.hpp \
		include/glm/detail/func_packing.hpp \
		include/glm/detail/func_packing.inl \
		include/glm/detail/type_half.hpp \
		include/glm/detail/type_half.inl \
		include/glm/geometric.hpp \
		include/glm/detail/func_geometric.hpp \
		include/glm/detail/func_geometric.inl \
		include/glm/matrix.hpp \
		include/glm/detail/func_matrix.hpp \
		include/glm/detail/func_matrix.inl \
		include/glm/vector_relational.hpp \
		include/glm/integer.hpp \
		include/glm/detail/func_integer.hpp \
		include/glm/detail/func_integer.inl \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o light.o light.cpp

board.o: board.cpp board.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qvector.h \
		mosquito.h \
		include/glm/glm.hpp \
		include/glm/detail/_fixes.hpp \
		include/glm/fwd.hpp \
		include/glm/detail/type_int.hpp \
		include/glm/detail/setup.hpp \
		include/glm/detail/type_float.hpp \
		include/glm/detail/type_vec.hpp \
		include/glm/detail/precision.hpp \
		include/glm/detail/type_mat.hpp \
		include/glm/vec2.hpp \
		include/glm/detail/type_vec2.hpp \
		include/glm/detail/_swizzle.hpp \
		include/glm/detail/_swizzle_func.hpp \
		include/glm/detail/type_vec2.inl \
		include/glm/vec3.hpp \
		include/glm/detail/type_vec3.hpp \
		include/glm/detail/type_vec3.inl \
		include/glm/vec4.hpp \
		include/glm/detail/type_vec4.hpp \
		include/glm/detail/type_vec4.inl \
		include/glm/mat2x2.hpp \
		include/glm/detail/type_mat2x2.hpp \
		include/glm/detail/type_mat2x2.inl \
		include/glm/mat2x3.hpp \
		include/glm/detail/type_mat2x3.hpp \
		include/glm/detail/type_mat2x3.inl \
		include/glm/mat2x4.hpp \
		include/glm/detail/type_mat2x4.hpp \
		include/glm/detail/type_mat2x4.inl \
		include/glm/mat3x2.hpp \
		include/glm/detail/type_mat3x2.hpp \
		include/glm/detail/type_mat3x2.inl \
		include/glm/mat3x3.hpp \
		include/glm/detail/type_mat3x3.hpp \
		include/glm/detail/type_mat3x3.inl \
		include/glm/mat3x4.hpp \
		include/glm/detail/type_mat3x4.hpp \
		include/glm/detail/type_mat3x4.inl \
		include/glm/mat4x2.hpp \
		include/glm/detail/type_mat4x2.hpp \
		include/glm/detail/type_mat4x2.inl \
		include/glm/mat4x3.hpp \
		include/glm/detail/type_mat4x3.hpp \
		include/glm/detail/type_mat4x3.inl \
		include/glm/mat4x4.hpp \
		include/glm/detail/type_mat4x4.hpp \
		include/glm/detail/type_mat4x4.inl \
		include/glm/trigonometric.hpp \
		include/glm/detail/func_trigonometric.hpp \
		include/glm/detail/func_trigonometric.inl \
		include/glm/detail/_vectorize.hpp \
		include/glm/detail/type_vec1.hpp \
		include/glm/detail/type_vec1.inl \
		include/glm/exponential.hpp \
		include/glm/detail/func_exponential.hpp \
		include/glm/detail/func_exponential.inl \
		include/glm/detail/func_vector_relational.hpp \
		include/glm/detail/func_vector_relational.inl \
		include/glm/common.hpp \
		include/glm/detail/func_common.hpp \
		include/glm/detail/func_common.inl \
		include/glm/packing.hpp \
		include/glm/detail/func_packing.hpp \
		include/glm/detail/func_packing.inl \
		include/glm/detail/type_half.hpp \
		include/glm/detail/type_half.inl \
		include/glm/geometric.hpp \
		include/glm/detail/func_geometric.hpp \
		include/glm/detail/func_geometric.inl \
		include/glm/matrix.hpp \
		include/glm/detail/func_matrix.hpp \
		include/glm/detail/func_matrix.inl \
		include/glm/vector_relational.hpp \
		include/glm/integer.hpp \
		include/glm/detail/func_integer.hpp \
		include/glm/detail/func_integer.inl \
		light.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		wall.h \
		frog.h \
		player.h \
		myplayer.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o board.o board.cpp

wall.o: wall.cpp wall.h \
		include/glm/glm.hpp \
		include/glm/detail/_fixes.hpp \
		include/glm/fwd.hpp \
		include/glm/detail/type_int.hpp \
		include/glm/detail/setup.hpp \
		include/glm/detail/type_float.hpp \
		include/glm/detail/type_vec.hpp \
		include/glm/detail/precision.hpp \
		include/glm/detail/type_mat.hpp \
		include/glm/vec2.hpp \
		include/glm/detail/type_vec2.hpp \
		include/glm/detail/_swizzle.hpp \
		include/glm/detail/_swizzle_func.hpp \
		include/glm/detail/type_vec2.inl \
		include/glm/vec3.hpp \
		include/glm/detail/type_vec3.hpp \
		include/glm/detail/type_vec3.inl \
		include/glm/vec4.hpp \
		include/glm/detail/type_vec4.hpp \
		include/glm/detail/type_vec4.inl \
		include/glm/mat2x2.hpp \
		include/glm/detail/type_mat2x2.hpp \
		include/glm/detail/type_mat2x2.inl \
		include/glm/mat2x3.hpp \
		include/glm/detail/type_mat2x3.hpp \
		include/glm/detail/type_mat2x3.inl \
		include/glm/mat2x4.hpp \
		include/glm/detail/type_mat2x4.hpp \
		include/glm/detail/type_mat2x4.inl \
		include/glm/mat3x2.hpp \
		include/glm/detail/type_mat3x2.hpp \
		include/glm/detail/type_mat3x2.inl \
		include/glm/mat3x3.hpp \
		include/glm/detail/type_mat3x3.hpp \
		include/glm/detail/type_mat3x3.inl \
		include/glm/mat3x4.hpp \
		include/glm/detail/type_mat3x4.hpp \
		include/glm/detail/type_mat3x4.inl \
		include/glm/mat4x2.hpp \
		include/glm/detail/type_mat4x2.hpp \
		include/glm/detail/type_mat4x2.inl \
		include/glm/mat4x3.hpp \
		include/glm/detail/type_mat4x3.hpp \
		include/glm/detail/type_mat4x3.inl \
		include/glm/mat4x4.hpp \
		include/glm/detail/type_mat4x4.hpp \
		include/glm/detail/type_mat4x4.inl \
		include/glm/trigonometric.hpp \
		include/glm/detail/func_trigonometric.hpp \
		include/glm/detail/func_trigonometric.inl \
		include/glm/detail/_vectorize.hpp \
		include/glm/detail/type_vec1.hpp \
		include/glm/detail/type_vec1.inl \
		include/glm/exponential.hpp \
		include/glm/detail/func_exponential.hpp \
		include/glm/detail/func_exponential.inl \
		include/glm/detail/func_vector_relational.hpp \
		include/glm/detail/func_vector_relational.inl \
		include/glm/common.hpp \
		include/glm/detail/func_common.hpp \
		include/glm/detail/func_common.inl \
		include/glm/packing.hpp \
		include/glm/detail/func_packing.hpp \
		include/glm/detail/func_packing.inl \
		include/glm/detail/type_half.hpp \
		include/glm/detail/type_half.inl \
		include/glm/geometric.hpp \
		include/glm/detail/func_geometric.hpp \
		include/glm/detail/func_geometric.inl \
		include/glm/matrix.hpp \
		include/glm/detail/func_matrix.hpp \
		include/glm/detail/func_matrix.inl \
		include/glm/vector_relational.hpp \
		include/glm/integer.hpp \
		include/glm/detail/func_integer.hpp \
		include/glm/detail/func_integer.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wall.o wall.cpp

frog.o: frog.cpp frog.h \
		include/glm/glm.hpp \
		include/glm/detail/_fixes.hpp \
		include/glm/fwd.hpp \
		include/glm/detail/type_int.hpp \
		include/glm/detail/setup.hpp \
		include/glm/detail/type_float.hpp \
		include/glm/detail/type_vec.hpp \
		include/glm/detail/precision.hpp \
		include/glm/detail/type_mat.hpp \
		include/glm/vec2.hpp \
		include/glm/detail/type_vec2.hpp \
		include/glm/detail/_swizzle.hpp \
		include/glm/detail/_swizzle_func.hpp \
		include/glm/detail/type_vec2.inl \
		include/glm/vec3.hpp \
		include/glm/detail/type_vec3.hpp \
		include/glm/detail/type_vec3.inl \
		include/glm/vec4.hpp \
		include/glm/detail/type_vec4.hpp \
		include/glm/detail/type_vec4.inl \
		include/glm/mat2x2.hpp \
		include/glm/detail/type_mat2x2.hpp \
		include/glm/detail/type_mat2x2.inl \
		include/glm/mat2x3.hpp \
		include/glm/detail/type_mat2x3.hpp \
		include/glm/detail/type_mat2x3.inl \
		include/glm/mat2x4.hpp \
		include/glm/detail/type_mat2x4.hpp \
		include/glm/detail/type_mat2x4.inl \
		include/glm/mat3x2.hpp \
		include/glm/detail/type_mat3x2.hpp \
		include/glm/detail/type_mat3x2.inl \
		include/glm/mat3x3.hpp \
		include/glm/detail/type_mat3x3.hpp \
		include/glm/detail/type_mat3x3.inl \
		include/glm/mat3x4.hpp \
		include/glm/detail/type_mat3x4.hpp \
		include/glm/detail/type_mat3x4.inl \
		include/glm/mat4x2.hpp \
		include/glm/detail/type_mat4x2.hpp \
		include/glm/detail/type_mat4x2.inl \
		include/glm/mat4x3.hpp \
		include/glm/detail/type_mat4x3.hpp \
		include/glm/detail/type_mat4x3.inl \
		include/glm/mat4x4.hpp \
		include/glm/detail/type_mat4x4.hpp \
		include/glm/detail/type_mat4x4.inl \
		include/glm/trigonometric.hpp \
		include/glm/detail/func_trigonometric.hpp \
		include/glm/detail/func_trigonometric.inl \
		include/glm/detail/_vectorize.hpp \
		include/glm/detail/type_vec1.hpp \
		include/glm/detail/type_vec1.inl \
		include/glm/exponential.hpp \
		include/glm/detail/func_exponential.hpp \
		include/glm/detail/func_exponential.inl \
		include/glm/detail/func_vector_relational.hpp \
		include/glm/detail/func_vector_relational.inl \
		include/glm/common.hpp \
		include/glm/detail/func_common.hpp \
		include/glm/detail/func_common.inl \
		include/glm/packing.hpp \
		include/glm/detail/func_packing.hpp \
		include/glm/detail/func_packing.inl \
		include/glm/detail/type_half.hpp \
		include/glm/detail/type_half.inl \
		include/glm/geometric.hpp \
		include/glm/detail/func_geometric.hpp \
		include/glm/detail/func_geometric.inl \
		include/glm/matrix.hpp \
		include/glm/detail/func_matrix.hpp \
		include/glm/detail/func_matrix.inl \
		include/glm/vector_relational.hpp \
		include/glm/integer.hpp \
		include/glm/detail/func_integer.hpp \
		include/glm/detail/func_integer.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frog.o frog.cpp

player.o: player.cpp player.h \
		include/glm/glm.hpp \
		include/glm/detail/_fixes.hpp \
		include/glm/fwd.hpp \
		include/glm/detail/type_int.hpp \
		include/glm/detail/setup.hpp \
		include/glm/detail/type_float.hpp \
		include/glm/detail/type_vec.hpp \
		include/glm/detail/precision.hpp \
		include/glm/detail/type_mat.hpp \
		include/glm/vec2.hpp \
		include/glm/detail/type_vec2.hpp \
		include/glm/detail/_swizzle.hpp \
		include/glm/detail/_swizzle_func.hpp \
		include/glm/detail/type_vec2.inl \
		include/glm/vec3.hpp \
		include/glm/detail/type_vec3.hpp \
		include/glm/detail/type_vec3.inl \
		include/glm/vec4.hpp \
		include/glm/detail/type_vec4.hpp \
		include/glm/detail/type_vec4.inl \
		include/glm/mat2x2.hpp \
		include/glm/detail/type_mat2x2.hpp \
		include/glm/detail/type_mat2x2.inl \
		include/glm/mat2x3.hpp \
		include/glm/detail/type_mat2x3.hpp \
		include/glm/detail/type_mat2x3.inl \
		include/glm/mat2x4.hpp \
		include/glm/detail/type_mat2x4.hpp \
		include/glm/detail/type_mat2x4.inl \
		include/glm/mat3x2.hpp \
		include/glm/detail/type_mat3x2.hpp \
		include/glm/detail/type_mat3x2.inl \
		include/glm/mat3x3.hpp \
		include/glm/detail/type_mat3x3.hpp \
		include/glm/detail/type_mat3x3.inl \
		include/glm/mat3x4.hpp \
		include/glm/detail/type_mat3x4.hpp \
		include/glm/detail/type_mat3x4.inl \
		include/glm/mat4x2.hpp \
		include/glm/detail/type_mat4x2.hpp \
		include/glm/detail/type_mat4x2.inl \
		include/glm/mat4x3.hpp \
		include/glm/detail/type_mat4x3.hpp \
		include/glm/detail/type_mat4x3.inl \
		include/glm/mat4x4.hpp \
		include/glm/detail/type_mat4x4.hpp \
		include/glm/detail/type_mat4x4.inl \
		include/glm/trigonometric.hpp \
		include/glm/detail/func_trigonometric.hpp \
		include/glm/detail/func_trigonometric.inl \
		include/glm/detail/_vectorize.hpp \
		include/glm/detail/type_vec1.hpp \
		include/glm/detail/type_vec1.inl \
		include/glm/exponential.hpp \
		include/glm/detail/func_exponential.hpp \
		include/glm/detail/func_exponential.inl \
		include/glm/detail/func_vector_relational.hpp \
		include/glm/detail/func_vector_relational.inl \
		include/glm/common.hpp \
		include/glm/detail/func_common.hpp \
		include/glm/detail/func_common.inl \
		include/glm/packing.hpp \
		include/glm/detail/func_packing.hpp \
		include/glm/detail/func_packing.inl \
		include/glm/detail/type_half.hpp \
		include/glm/detail/type_half.inl \
		include/glm/geometric.hpp \
		include/glm/detail/func_geometric.hpp \
		include/glm/detail/func_geometric.inl \
		include/glm/matrix.hpp \
		include/glm/detail/func_matrix.hpp \
		include/glm/detail/func_matrix.inl \
		include/glm/vector_relational.hpp \
		include/glm/integer.hpp \
		include/glm/detail/func_integer.hpp \
		include/glm/detail/func_integer.inl \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		wall.h \
		light.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

myplayer.o: myplayer.cpp myplayer.h \
		player.h \
		include/glm/glm.hpp \
		include/glm/detail/_fixes.hpp \
		include/glm/fwd.hpp \
		include/glm/detail/type_int.hpp \
		include/glm/detail/setup.hpp \
		include/glm/detail/type_float.hpp \
		include/glm/detail/type_vec.hpp \
		include/glm/detail/precision.hpp \
		include/glm/detail/type_mat.hpp \
		include/glm/vec2.hpp \
		include/glm/detail/type_vec2.hpp \
		include/glm/detail/_swizzle.hpp \
		include/glm/detail/_swizzle_func.hpp \
		include/glm/detail/type_vec2.inl \
		include/glm/vec3.hpp \
		include/glm/detail/type_vec3.hpp \
		include/glm/detail/type_vec3.inl \
		include/glm/vec4.hpp \
		include/glm/detail/type_vec4.hpp \
		include/glm/detail/type_vec4.inl \
		include/glm/mat2x2.hpp \
		include/glm/detail/type_mat2x2.hpp \
		include/glm/detail/type_mat2x2.inl \
		include/glm/mat2x3.hpp \
		include/glm/detail/type_mat2x3.hpp \
		include/glm/detail/type_mat2x3.inl \
		include/glm/mat2x4.hpp \
		include/glm/detail/type_mat2x4.hpp \
		include/glm/detail/type_mat2x4.inl \
		include/glm/mat3x2.hpp \
		include/glm/detail/type_mat3x2.hpp \
		include/glm/detail/type_mat3x2.inl \
		include/glm/mat3x3.hpp \
		include/glm/detail/type_mat3x3.hpp \
		include/glm/detail/type_mat3x3.inl \
		include/glm/mat3x4.hpp \
		include/glm/detail/type_mat3x4.hpp \
		include/glm/detail/type_mat3x4.inl \
		include/glm/mat4x2.hpp \
		include/glm/detail/type_mat4x2.hpp \
		include/glm/detail/type_mat4x2.inl \
		include/glm/mat4x3.hpp \
		include/glm/detail/type_mat4x3.hpp \
		include/glm/detail/type_mat4x3.inl \
		include/glm/mat4x4.hpp \
		include/glm/detail/type_mat4x4.hpp \
		include/glm/detail/type_mat4x4.inl \
		include/glm/trigonometric.hpp \
		include/glm/detail/func_trigonometric.hpp \
		include/glm/detail/func_trigonometric.inl \
		include/glm/detail/_vectorize.hpp \
		include/glm/detail/type_vec1.hpp \
		include/glm/detail/type_vec1.inl \
		include/glm/exponential.hpp \
		include/glm/detail/func_exponential.hpp \
		include/glm/detail/func_exponential.inl \
		include/glm/detail/func_vector_relational.hpp \
		include/glm/detail/func_vector_relational.inl \
		include/glm/common.hpp \
		include/glm/detail/func_common.hpp \
		include/glm/detail/func_common.inl \
		include/glm/packing.hpp \
		include/glm/detail/func_packing.hpp \
		include/glm/detail/func_packing.inl \
		include/glm/detail/type_half.hpp \
		include/glm/detail/type_half.inl \
		include/glm/geometric.hpp \
		include/glm/detail/func_geometric.hpp \
		include/glm/detail/func_geometric.inl \
		include/glm/matrix.hpp \
		include/glm/detail/func_matrix.hpp \
		include/glm/detail/func_matrix.inl \
		include/glm/vector_relational.hpp \
		include/glm/integer.hpp \
		include/glm/detail/func_integer.hpp \
		include/glm/detail/func_integer.inl \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		wall.h \
		light.h \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myplayer.o myplayer.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

